## Corrección del Examen de 1er bimestre

In [14]:
##Jair Sanchez

Considere el siguiente corpus:

In [15]:
doc1 = "Las habilidades blandas son fundamentales para el éxito en el campo de la informática. Estas habilidades fundamentales incluyen la comunicación efectiva, la capacidad de trabajar en equipo y la gestión del tiempo."
doc2 = "El desarrollo de habilidades blandas es fundamental para los informáticos, ya que estas competencias facilitan la interacción y colaboración en entornos de trabajo dinámicos."
doc3 = "En la informática, la resolución de problemas es una habilidad técnica esencial, pero combinarla con habilidades blandas como la creatividad y el pensamiento crítico puede llevar a soluciones innovadoras."
doc4 = "La empatía, por ejemplo, es una habilidad blanda que permite a los profesionales de la informática entender y anticipar las necesidades fundamentales de los usuarios, mejorando así la calidad de los productos y técnicas desarrolladas."
doc5 = "La inteligencia emocional es una habilidad blanda vital para los informáticos. Permite gestionar mejor las emociones propias y las de los demás, facilitando así un entorno de trabajo más armonioso y productivo."

# wset es el conjunto de palabras en el corpus
wset = set()
# docs es el arreglo de documentos en el corpus
docs = [doc1, doc2, doc3, doc4, doc5]

#### 0. Preprocesamiento del corpus

Considere las siguientes palabras vacías, o stop words:
{a, así, como, con, de, del, el, en, es, estas, la, las, los, más, para, pero, por, que, son, un, una, y, ya}

In [16]:
import string
from collections import defaultdict

stopw = ['la','de','y','los','las','el','en','es','para','una','estas','a','así','son','del','ya','que','pero','con','como','por','un','más']
# stopw = []

word_counts = defaultdict(int)
for doc in docs:
    for word in doc.lower().translate(str.maketrans('', '', string.punctuation)).split(" "):
        if word not in stopw:
            wset.add(word)
            word_counts[word.lower()] += 1

# sorted_word_count es un arreglo de términos con su respectivo conteo
# está ordenado del término más frecuente al menos frecuente
sorted_word_count = sorted(word_counts.items(), key=lambda item: item[1], reverse=True)
print(sorted_word_count)

[('habilidades', 4), ('blandas', 3), ('fundamentales', 3), ('informática', 3), ('habilidad', 3), ('informáticos', 2), ('trabajo', 2), ('blanda', 2), ('permite', 2), ('éxito', 1), ('campo', 1), ('incluyen', 1), ('comunicación', 1), ('efectiva', 1), ('capacidad', 1), ('trabajar', 1), ('equipo', 1), ('gestión', 1), ('tiempo', 1), ('desarrollo', 1), ('fundamental', 1), ('competencias', 1), ('facilitan', 1), ('interacción', 1), ('colaboración', 1), ('entornos', 1), ('dinámicos', 1), ('resolución', 1), ('problemas', 1), ('técnica', 1), ('esencial', 1), ('combinarla', 1), ('creatividad', 1), ('pensamiento', 1), ('crítico', 1), ('puede', 1), ('llevar', 1), ('soluciones', 1), ('innovadoras', 1), ('empatía', 1), ('ejemplo', 1), ('profesionales', 1), ('entender', 1), ('anticipar', 1), ('necesidades', 1), ('usuarios', 1), ('mejorando', 1), ('calidad', 1), ('productos', 1), ('técnicas', 1), ('desarrolladas', 1), ('inteligencia', 1), ('emocional', 1), ('vital', 1), ('gestionar', 1), ('mejor', 1), ('

In [17]:
# se repite el procesamiento anterior de conteo de palabras, integrando la actividad de Stemming
from nltk.stem import SnowballStemmer

stemmer = SnowballStemmer('spanish')
stopw = ['la','de','y','los','lo','las','el','en','es','para','una','estas', 'esta','a','así','son','del','ya','que','pero','con','como','por','un','más','má','demá', 'par','asi']
# stopw = []

stem_docs = []
for doc in docs:
    sdoc = []
    for word in doc.lower().translate(str.maketrans('', '', string.punctuation)).split(" "):
        if word not in stopw:
            sdoc.append(stemmer.stem(word))
    stem_docs.append(sdoc)

word_counts = defaultdict(int)
for doc in docs:
    for word in doc.lower().translate(str.maketrans('', '', string.punctuation)).split(" "):
        word = stemmer.stem(word)
        if word not in stopw:
            wset.add(word)
            word_counts[word.lower()] += 1
            
sorted_word_count = sorted(word_counts.items(), key=lambda item: item[1], reverse=True)
print(sorted_word_count)

[('habil', 7), ('bland', 5), ('informat', 5), ('fundamental', 4), ('trabaj', 3), ('gestion', 2), ('desarroll', 2), ('facilit', 2), ('entorn', 2), ('tecnic', 2), ('permit', 2), ('mejor', 2), ('product', 2), ('exit', 1), ('camp', 1), ('inclu', 1), ('comun', 1), ('efect', 1), ('capac', 1), ('equip', 1), ('tiemp', 1), ('competent', 1), ('interaccion', 1), ('colabor', 1), ('dinam', 1), ('resolu', 1), ('problem', 1), ('esencial', 1), ('per', 1), ('combin', 1), ('com', 1), ('creativ', 1), ('pensamient', 1), ('critic', 1), ('pued', 1), ('llev', 1), ('solucion', 1), ('innov', 1), ('empat', 1), ('ejempl', 1), ('profesional', 1), ('entend', 1), ('anticip', 1), ('neces', 1), ('usuari', 1), ('calid', 1), ('inteligent', 1), ('emocional', 1), ('vital', 1), ('emocion', 1), ('propi', 1), ('demas', 1), ('mas', 1), ('armoni', 1)]


#### 1. Determine un espacio vectorial para la representación de documentos con 10 dimensiones. Considere a las palabras a partir de su raíz, para simplificar su representación computacional.

In [18]:
ev = sorted_word_count[2:11]
ev.append(sorted_word_count[36])
print(ev)

[('informat', 5), ('fundamental', 4), ('trabaj', 3), ('gestion', 2), ('desarroll', 2), ('facilit', 2), ('entorn', 2), ('tecnic', 2), ('permit', 2), ('solucion', 1)]


#### 2. Construya una matriz binaria de incidencias (presencia/ausencia)

In [19]:
# ev_docs es un arreglo con la representación binaria (presencia/ausencia) de los documentos en el espacio vectorial
ev_docs = []
for doc in stem_docs:
    ev_doc = []
    for dim in ev:
        if dim[0] in doc:
            ev_doc.append(1)
        else:
            ev_doc.append(0)
    ev_docs.append(ev_doc)
print(ev_docs)

[[1, 1, 1, 1, 0, 0, 0, 0, 0, 0], [1, 1, 1, 0, 1, 1, 1, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 1, 0, 1], [1, 1, 0, 0, 1, 0, 0, 1, 1, 0], [1, 0, 1, 1, 0, 1, 1, 0, 1, 0]]


#### 3. Utilizando la similitud Jaccard, determine cuáles son los documentos por recuperarse para las siguientes consultas:
3.1. “habilidad” AND “blanda” AND “fundamental”

3.2. “habilidad” AND “blanda” AND NOT “técnica”

3.3. “gestión” OR “solución”

In [20]:
# hablidad AND blanda AND fundamental
q1 = [0,1,0,0,0,0,0,0,0,0]
# hablidad AND blanda AND NOT técnica
q2 = [1,1,1,1,1,1,1,0,1,1]
# gestión OR solución
q3 = [0,0,0,1,0,0,0,0,0,1]

queries = [q1,q2,q3]
read_queries = ['hablidad AND blanda AND fundamental', 'hablidad AND blanda AND NOT técnica', 'gestión OR solución']

Similitud Jaccard: $JSim=|Q\cap D|/|Q\cup D|$

In [21]:
def jsim(q,d):
    c = 0
    for i in range(len(q)):
        # contar los elementos iguales a 1 que son comunes entre los dos conjuntos
        if q[i] == d[i] and d[i] == 1:
            c += 1
    f = 0
    for i in range(len(q)):
        # contar los elementos iguales a 1 en cualquiera de los dos conjuntos
        if q[i] == 1 or d[i] == 1:
            f += 1
    #print('c',c,'f',f)
    return c/f

In [22]:
for i in range(len(queries)):
    print('-------------------------------------------------------')
    print('QUERY: ',i,read_queries[i])
    for j in range(0,len(ev_docs)):
        #print(queries[i],ev_docs[j])
        jsim_ = jsim(queries[i],ev_docs[j])
        if jsim_ > 0:
            print('doc',j,'Jsim',jsim_)
            print(docs[j])

-------------------------------------------------------
QUERY:  0 hablidad AND blanda AND fundamental
doc 0 Jsim 0.25
Las habilidades blandas son fundamentales para el éxito en el campo de la informática. Estas habilidades fundamentales incluyen la comunicación efectiva, la capacidad de trabajar en equipo y la gestión del tiempo.
doc 1 Jsim 0.16666666666666666
El desarrollo de habilidades blandas es fundamental para los informáticos, ya que estas competencias facilitan la interacción y colaboración en entornos de trabajo dinámicos.
doc 3 Jsim 0.2
La empatía, por ejemplo, es una habilidad blanda que permite a los profesionales de la informática entender y anticipar las necesidades fundamentales de los usuarios, mejorando así la calidad de los productos y técnicas desarrolladas.
-------------------------------------------------------
QUERY:  1 hablidad AND blanda AND NOT técnica
doc 0 Jsim 0.4444444444444444
Las habilidades blandas son fundamentales para el éxito en el campo de la inform

#### 4. Con el mismo espacio vectorial del punto 1, construya una matriz de términos y documentos (matriz TF-IDF).

Frecuencia de término: $TF_{ij}=count(t_i,d_j)/|d_j|$

Frecuencia inversa de término: $IDF_{ij} = log(|corpus|/count(d_j,t_i))$

In [23]:
import numpy as np
import math

# Términos del espacio vectorial (obtenidos previamente)
terms = [term for term, _ in ev]

# Crear la matriz TF (Frecuencia de Término)
tf_matrix = np.zeros((len(terms), len(docs)))

for doc_index, doc in enumerate(stem_docs):
    for term_index, term in enumerate(terms):
        tf_matrix[term_index, doc_index] = doc.count(term) / len(doc)

# Calcular IDF para cada término
idf = np.zeros(len(terms))
total_docs = len(docs)

for term_index, term in enumerate(terms):
    containing_docs = sum(1 for doc in stem_docs if term in doc)
    idf[term_index] = math.log(total_docs / (1 + containing_docs))

# Calcular la matriz TF-IDF
tfidf_matrix = tf_matrix * idf[:, None]

# Mostrar la matriz TF-IDF
print("Matriz TF-IDF:")
print(tfidf_matrix)


Matriz TF-IDF:
[[-0.0113951  -0.01519346 -0.0113951  -0.0107248  -0.0107248 ]
 [ 0.02789294  0.0185953   0.          0.01312609  0.        ]
 [ 0.01394647  0.0185953   0.          0.          0.01312609]
 [ 0.0319266   0.          0.          0.          0.03004857]
 [ 0.          0.0425688   0.          0.03004857  0.        ]
 [ 0.          0.0425688   0.          0.          0.03004857]
 [ 0.          0.0425688   0.          0.          0.03004857]
 [ 0.          0.          0.0319266   0.03004857  0.        ]
 [ 0.          0.          0.          0.03004857  0.03004857]
 [ 0.          0.          0.05726817  0.          0.        ]]


#### 5. Calcule el vector de la consulta utilizando las mismas fórmulas de TF-IDF.

In [24]:
import numpy as np
import math

# Términos del espacio vectorial (obtenidos previamente)
terms = [term for term, _ in ev]

# Crear una función para procesar la consulta
def process_query(query, terms, idf):
    # Tokenizar y realizar el stemming de la consulta
    query_tokens = query.lower().translate(str.maketrans('', '', string.punctuation)).split(" ")
    stemmed_query = [stemmer.stem(word) for word in query_tokens if word not in stopw]
    
    # Calcular la frecuencia de término (TF) para la consulta
    tf_query = np.zeros(len(terms))
    for term_index, term in enumerate(terms):
        tf_query[term_index] = stemmed_query.count(term) / len(stemmed_query)
    
    # Calcular el vector TF-IDF de la consulta
    tfidf_query = tf_query * idf
    return tfidf_query

# Ejemplos de consultas
query1 = "habilidad blanda fundamental"
query2 = "habilidad blanda NOT técnica"
query3 = "gestión OR solución"

# Calcular los vectores TF-IDF de las consultas
tfidf_query1 = process_query(query1, terms, idf)
tfidf_query2 = process_query(query2, terms, idf)
tfidf_query3 = process_query(query3, terms, idf)

# Mostrar los vectores TF-IDF de las consultas
print("TF-IDF vector for query 1:", tfidf_query1)
print("TF-IDF vector for query 2:", tfidf_query2)
print("TF-IDF vector for query 3:", tfidf_query3)


TF-IDF vector for query 1: [-0.          0.07438118  0.          0.          0.          0.
  0.          0.          0.          0.        ]
TF-IDF vector for query 2: [-0.          0.          0.          0.          0.          0.
  0.          0.12770641  0.          0.        ]
TF-IDF vector for query 3: [-0.          0.          0.          0.17027521  0.          0.
  0.          0.          0.          0.30543024]


#### 6. Utilizando la similitud coseno, determine cuáles son los documentos por recuperarse para las siguientes consultas:
6.1. “habilidades blandas fundamentales”

6.2. “habilidades técnicas”

6.3. “solución y gestión en informática”

In [25]:
import numpy as np
import math
from sklearn.metrics.pairwise import cosine_similarity

# Crear una función para procesar la consulta
def process_query(query, terms, idf):
    # Tokenizar y realizar el stemming de la consulta
    query_tokens = query.lower().translate(str.maketrans('', '', string.punctuation)).split(" ")
    stemmed_query = [stemmer.stem(word) for word in query_tokens if word not in stopw]
    
    # Calcular la frecuencia de término (TF) para la consulta
    tf_query = np.zeros(len(terms))
    for term_index, term in enumerate(terms):
        tf_query[term_index] = stemmed_query.count(term) / len(stemmed_query)
    
    # Calcular el vector TF-IDF de la consulta
    tfidf_query = tf_query * idf
    return tfidf_query

# Ejemplos de consultas
query1 = "habilidades blandas fundamentales"
query2 = "habilidades técnicas"
query3 = "solución y gestión en informática"

# Calcular los vectores TF-IDF de las consultas
tfidf_query1 = process_query(query1, terms, idf)
tfidf_query2 = process_query(query2, terms, idf)
tfidf_query3 = process_query(query3, terms, idf)

# Mostrar los vectores TF-IDF de las consultas
print("TF-IDF vector for query 1:", tfidf_query1)
print("TF-IDF vector for query 2:", tfidf_query2)
print("TF-IDF vector for query 3:", tfidf_query3)


TF-IDF vector for query 1: [-0.          0.07438118  0.          0.          0.          0.
  0.          0.          0.          0.        ]
TF-IDF vector for query 2: [-0.          0.          0.          0.          0.          0.
  0.          0.25541281  0.          0.        ]
TF-IDF vector for query 3: [-0.06077385  0.          0.          0.17027521  0.          0.
  0.          0.          0.          0.30543024]


In [26]:
# Calcular la matriz de similitud coseno entre la consulta y los documentos
def calculate_cosine_similarity(tfidf_query, tfidf_matrix):
    # Convertir tfidf_query a 2D array para usar en cosine_similarity
    tfidf_query_2d = tfidf_query.reshape(1, -1)
    similarities = cosine_similarity(tfidf_query_2d, tfidf_matrix.T)[0]
    return similarities

# Calcular la similitud coseno para cada consulta
cosine_sim_query1 = calculate_cosine_similarity(tfidf_query1, tfidf_matrix)
cosine_sim_query2 = calculate_cosine_similarity(tfidf_query2, tfidf_matrix)
cosine_sim_query3 = calculate_cosine_similarity(tfidf_query3, tfidf_matrix)

# Mostrar los documentos recuperados para cada consulta ordenados por similitud coseno
def print_retrieved_docs(query, cosine_similarities):
    print(f"Query: {query}")
    doc_indices = np.argsort(cosine_similarities)[::-1]  # Ordenar de mayor a menor
    for index in doc_indices:
        if cosine_similarities[index] > 0:  # Mostrar solo documentos con similitud > 0
            print(f"Document {index+1} with cosine similarity: {cosine_similarities[index]:.4f}")
            print(docs[index])
            print()

# Resultados para cada consulta
print_retrieved_docs(query1, cosine_sim_query1)
print_retrieved_docs(query2, cosine_sim_query2)
print_retrieved_docs(query3, cosine_sim_query3)


Query: habilidades blandas fundamentales
Document 1 with cosine similarity: 0.6056
Las habilidades blandas son fundamentales para el éxito en el campo de la informática. Estas habilidades fundamentales incluyen la comunicación efectiva, la capacidad de trabajar en equipo y la gestión del tiempo.

Document 4 with cosine similarity: 0.2398
La empatía, por ejemplo, es una habilidad blanda que permite a los profesionales de la informática entender y anticipar las necesidades fundamentales de los usuarios, mejorando así la calidad de los productos y técnicas desarrolladas.

Document 2 with cosine similarity: 0.2332
El desarrollo de habilidades blandas es fundamental para los informáticos, ya que estas competencias facilitan la interacción y colaboración en entornos de trabajo dinámicos.

Query: habilidades técnicas
Document 4 with cosine similarity: 0.5490
La empatía, por ejemplo, es una habilidad blanda que permite a los profesionales de la informática entender y anticipar las necesidades 

#### 7. Ordene los documentos en función de su similitud con la consulta, de mayor a menor.

In [27]:
# Función para ordenar y mostrar documentos en función de su similitud con la consulta
def order_documents_by_similarity(query, cosine_similarities):
    print(f"Query: {query}")
    doc_indices = np.argsort(cosine_similarities)[::-1]  # Ordenar de mayor a menor
    ordered_docs = [(index+1, cosine_similarities[index], docs[index]) for index in doc_indices if cosine_similarities[index] > 0]
    for doc_index, sim, doc in ordered_docs:
        print(f"Document {doc_index} with cosine similarity: {sim:.4f}")
        print(doc)
        print()
    return ordered_docs

# Ordenar y mostrar los documentos para cada consulta
ordered_docs_query1 = order_documents_by_similarity(query1, cosine_sim_query1)
ordered_docs_query2 = order_documents_by_similarity(query2, cosine_sim_query2)
ordered_docs_query3 = order_documents_by_similarity(query3, cosine_sim_query3)


Query: habilidades blandas fundamentales
Document 1 with cosine similarity: 0.6056
Las habilidades blandas son fundamentales para el éxito en el campo de la informática. Estas habilidades fundamentales incluyen la comunicación efectiva, la capacidad de trabajar en equipo y la gestión del tiempo.

Document 4 with cosine similarity: 0.2398
La empatía, por ejemplo, es una habilidad blanda que permite a los profesionales de la informática entender y anticipar las necesidades fundamentales de los usuarios, mejorando así la calidad de los productos y técnicas desarrolladas.

Document 2 with cosine similarity: 0.2332
El desarrollo de habilidades blandas es fundamental para los informáticos, ya que estas competencias facilitan la interacción y colaboración en entornos de trabajo dinámicos.

Query: habilidades técnicas
Document 4 with cosine similarity: 0.5490
La empatía, por ejemplo, es una habilidad blanda que permite a los profesionales de la informática entender y anticipar las necesidades 

#### 8. Determine cuál es el documento más relevante para la consulta dada.

In [28]:
# Función para determinar el documento más relevante para la consulta dada
def most_relevant_document(ordered_docs):
    if ordered_docs:
        most_relevant = ordered_docs[0]  # El primer documento en la lista ordenada
        print(f"The most relevant document is Document {most_relevant[0]} with cosine similarity: {most_relevant[1]:.4f}")
        print(most_relevant[2])
    else:
        print("No relevant documents found.")

# Determinar y mostrar el documento más relevante para cada consulta
print("Most relevant document for Query 1:")
most_relevant_document(ordered_docs_query1)

print("\nMost relevant document for Query 2:")
most_relevant_document(ordered_docs_query2)

print("\nMost relevant document for Query 3:")
most_relevant_document(ordered_docs_query3)


Most relevant document for Query 1:
The most relevant document is Document 1 with cosine similarity: 0.6056
Las habilidades blandas son fundamentales para el éxito en el campo de la informática. Estas habilidades fundamentales incluyen la comunicación efectiva, la capacidad de trabajar en equipo y la gestión del tiempo.

Most relevant document for Query 2:
The most relevant document is Document 4 with cosine similarity: 0.5490
La empatía, por ejemplo, es una habilidad blanda que permite a los profesionales de la informática entender y anticipar las necesidades fundamentales de los usuarios, mejorando así la calidad de los productos y técnicas desarrolladas.

Most relevant document for Query 3:
The most relevant document is Document 3 with cosine similarity: 0.7698
En la informática, la resolución de problemas es una habilidad técnica esencial, pero combinarla con habilidades blandas como la creatividad y el pensamiento crítico puede llevar a soluciones innovadoras.
